import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Brain, 
  Target, 
  Calendar, 
  TrendingUp, 
  Zap, 
  Shield,
  ArrowRight,
  CheckCircle
} from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Planning',
    description: 'Get personalized workout plans generated by advanced AI that adapts to your goals and equipment.'
  },
  {
    icon: Target,
    title: 'Goal-Oriented',
    description: 'Whether you want to build strength, endurance, or lose weight, our AI creates plans tailored to your objectives.'
  },
  {
    icon: Calendar,
    title: 'Smart Scheduling',
    description: 'Plans that fit your schedule with automatic calendar integration and flexible timing options.'
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Track your workouts, RPE, and get insights into your progress with detailed analytics.'
  },
  {
    icon: Zap,
    title: 'Adaptive Intelligence',
    description: 'Your plans evolve based on your feedback, performance, and preferences each week.'
  },
  {
    icon: Shield,
    title: 'Safety First',
    description: 'Built-in injury prevention and exercise modifications based on your physical limitations.'
  }
];

const benefits = [
  'Personalized 5-day workout plans',
  'Real-time plan adaptation',
  'Progress tracking and analytics',
  'Calendar export (ICS format)',
  'No equipment limitations',
  'Injury-aware planning'
];

const Home = () => {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-primary-600 via-primary-700 to-primary-800">
        <div className="absolute inset-0 bg-black opacity-10"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center"
          >
            <h1 className="text-5xl md:text-6xl font-bold text-white mb-6">
              Your AI Workout
              <span className="block bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent">
                Personal Trainer
              </span>
            </h1>
            <p className="text-xl text-primary-100 mb-8 max-w-3xl mx-auto leading-relaxed">
              Get personalized workout plans that adapt to your progress, goals, and feedback. 
              Powered by advanced AI and designed to evolve with you.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center relative z-10">
              <Link
                to="/onboarding"
                className="inline-flex items-center justify-center px-8 py-4 text-lg font-semibold rounded-lg text-blue-800 hover:bg-gray-100 transition-all transform hover:scale-105 shadow-lg border border-gray-200 cursor-pointer"
                style={{
                  backgroundColor: 'white',
                  color: '#1e40af',
                  padding: '16px 32px',
                  borderRadius: '8px',
                  textDecoration: 'none',
                  fontWeight: '600',
                  fontSize: '18px',
                  boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                  border: '1px solid #e5e7eb',
                  zIndex: '10',
                  position: 'relative',
                  pointerEvents: 'auto'
                }}
              >
                Start Your Journey
                <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
              <a
                href="#features"
                className="inline-flex items-center justify-center px-8 py-4 text-lg font-semibold rounded-lg border-2 border-white text-white hover:bg-white transition-all cursor-pointer"
                style={{
                  backgroundColor: 'transparent',
                  color: 'white',
                  padding: '16px 32px',
                  borderRadius: '8px',
                  textDecoration: 'none',
                  fontWeight: '600',
                  fontSize: '18px',
                  border: '2px solid white',
                  zIndex: '10',
                  position: 'relative',
                  pointerEvents: 'auto'
                }}
              >
                Learn More
              </a>
            </div>
          </motion.div>
        </div>
        
        {/* Animated background elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-white opacity-5 rounded-full"></div>
          <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-white opacity-5 rounded-full"></div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Intelligent Fitness Planning
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Experience the future of personal training with AI that understands your unique needs and adapts to your progress.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="card hover:shadow-lg transition-shadow"
              >
                <div className="p-2 bg-primary-100 rounded-lg w-fit mb-4">
                  <feature.icon className="h-6 w-6 text-primary-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-24 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl font-bold text-gray-900 mb-6">
                Everything you need for
                <span className="text-primary-600"> successful workouts</span>
              </h2>
              <p className="text-lg text-gray-600 mb-8">
                Our AI trainer provides comprehensive support from plan generation to progress tracking, 
                ensuring you stay motivated and see results.
              </p>
              
              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <motion.div
                    key={benefit}
                    initial={{ opacity: 0, x: -20 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    viewport={{ once: true }}
                    className="flex items-center space-x-3"
                  >
                    <CheckCircle className="h-5 w-5 text-success-600 flex-shrink-0" />
                    <span className="text-gray-700">{benefit}</span>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="bg-gradient-to-br from-primary-500 to-primary-600 rounded-2xl p-8 text-white">
                <h3 className="text-2xl font-bold mb-4">Ready to get started?</h3>
                <p className="text-primary-100 mb-6">
                  Join thousands of users who have transformed their fitness journey with AI-powered training.
                </p>
                <Link
                  to="/onboarding"
                  className="inline-flex items-center justify-center w-full px-6 py-3 text-base font-semibold rounded-lg text-blue-800 hover:bg-gray-100 transition-all cursor-pointer"
                  style={{
                    backgroundColor: 'white',
                    color: '#1e40af',
                    padding: '12px 24px',
                    borderRadius: '8px',
                    textDecoration: 'none',
                    fontWeight: '600',
                    fontSize: '16px',
                    zIndex: '10',
                    position: 'relative',
                    pointerEvents: 'auto'
                  }}
                >
                  Start Free Trial
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </div>
              
              {/* Decorative elements */}
              <div className="absolute -top-4 -right-4 w-24 h-24 bg-primary-300 rounded-full opacity-20"></div>
              <div className="absolute -bottom-4 -left-4 w-16 h-16 bg-primary-400 rounded-full opacity-30"></div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-gray-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold text-white mb-4">
              Ready to revolutionize your workouts?
            </h2>
            <p className="text-gray-300 mb-8 text-lg">
              Start your personalized fitness journey today with AI-powered training that adapts to you.
            </p>
            <Link
              to="/onboarding"
              className="inline-flex items-center justify-center px-8 py-4 text-lg font-semibold rounded-lg text-white hover:opacity-90 transform hover:scale-105 transition-all shadow-lg cursor-pointer"
              style={{
                backgroundColor: '#0284c7',
                color: 'white',
                padding: '16px 32px',
                borderRadius: '8px',
                textDecoration: 'none',
                fontWeight: '600',
                fontSize: '18px',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                zIndex: '10',
                position: 'relative',
                pointerEvents: 'auto'
              }}
            >
              Get Started Now
              <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default Home;
